### ISSUE TITLE
好多报错

### ISSUE THREAD

**Issue by Sydrr0** [FengLiuFeseliud/pycqBot#20]
我在start（）加入了自己的地址，bot.start('D:\mybot\go-cqhttp.exe')，是为了解绝不是内部命令的问题，然后运行报错：
Exception in thread cqhttp_shell:
Traceback (most recent call last):
  File "C:\Users\JackyZ\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\JackyZ\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\JackyZ\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycqBot\cqApi.py", line 810, in cqhttp_start
    self._set_config(go_cqhttp_path)
  File "C:\Users\JackyZ\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycqBot\cqApi.py", line 801, in _set_config
    with open(config_path, "w", encoding="utf8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\mybot\\go-cqhttp.exe\\./config.yml'

**Comment by FengLiuFeseliud** [comment]
请将 go-cqhttp 放在 bot.start 文件的目录下

**Comment by Sydrr0** [comment]
这个目录在哪里呢

**Comment by Sydrr0** [comment]
![QQ截图20230507120109](https://user-images.githubusercontent.com/129657153/236656936-f2b45fd4-d6c5-4844-b7f6-191e480aacfa.png)

**Comment by Sydrr0** [comment]
> 请将 go-cqhttp 放在 bot.start 文件的目录下

还是得改源文件的目录地址，'./'貌似没有用处，或者在加一个os获取目录
