### ISSUE TITLE
cannot import name 'cqBot' from 'pycqBot.cqApi'

### ISSUE THREAD

**Issue by ChocolateJin** [FengLiuFeseliud/pycqBot#26]
用的Anaconda，python版本3.9.13，pycqbot版本0.5.1.1 go-cqhttp版本1.0.1.按照教程的模板编写了main.py和myPlugin.py后加载插件失败提示cannot import name 'cqBot' from 'pycqBot.cqApi'。
以下为main.py和myPlugin.py的内容
from pycqBot import cqHttpApi, cqLog
cqLog()

cqapi = cqHttpApi()
bot = cqapi.create_bot()

bot.plugin_load(["myPlugin"])

bot.start(print_error=False)

myPlugin.py

from pycqBot.cqApi import cqBot, cqHttpApi
from pycqBot.object import Plugin
from pycqBot.data import *

class myPlugin(Plugin):

    def __init__(self, bot: cqBot, cqapi: cqHttpApi, plugin_config):
        super().__init__(bot, cqapi, plugin_config)

        bot.command(self.test_plugin, "test", {
            "type": "all"
        })
    
    def test_plugin(self, cdata, message: Message):
        message.reply("this 插件 myPlugin")

以下是运行bot.plugin_load(["myPlugin"])这行时的报错：
[2023-05-11 21:37:08,353][MainThread/ERROR] PyCqBot: 加载插件 myPlugin 时发生错误: cannot import name 'cqBot' from 'pycqBot.cqApi' (D:\anaconda3\lib\site-packages\pycqBot\cqApi.py)
[2023-05-11 21:37:08,354][MainThread/ERROR] PyCqBot: cannot import name 'cqBot' from 'pycqBot.cqApi' (D:\anaconda3\lib\site-packages\pycqBot\cqApi.py)
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\pycqBot\cqHttpApi.py", line 429, in _import_plugin
    plugin_obj = importlib.import_module(f"plugin.{plugin}.{plugin}")
  File "D:\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\go-cqhttp\plugin\myPlugin.py", line 1, in <module>
    from pycqBot.cqApi import cqBot, cqHttpApi
ImportError: cannot import name 'cqBot' from 'pycqBot.cqApi' (D:\anaconda3\lib\site-packages\pycqBot\cqApi.py)
[2023-05-11 21:37:08,357][MainThread/INFO] PyCqBot: 加载插件: ['myPlugin']

**Comment by FengLiuFeseliud** [comment]
这么明显了，文档没改，你自己改一下引用就行
