### ISSUE TITLE
内置pixiv插件无法正常被加载

### ISSUE THREAD

**Issue by Hinatamoon** [FengLiuFeseliud/pycqBot#3]
在能正常运行的文件中加入

```
bot.plugin_load([
    "pycqBot.plugin.pixiv"   
])
```

后会报错
报错信息:
```
PS E:\Qbot> & C:/Users/Administrator/AppData/Local/Programs/Python/Python310/python.exe e:/Qbot/main.py
[2022-11-26 11:36:21,916][MainThread/DEBUG] PyCqBot: Using proactor: IocpProactor
Traceback (most recent call last):
  File "e:\Qbot\main.py", line 225, in <module>
    bot.plugin_load([
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pycqBot\cqApi.py", line 592, in plugin_load
    plugin_config = self._import_plugin_config()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pycqBot\cqApi.py", line 552, in _import_plugin_config
    return yaml.safe_load(file.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 60: illegal multibyte sequence
PS E:\Qbot>
```

plugin_config.yml
```
pixiv: 
    forward_qq: 2701711299
    forward_name: "胡桃ちゃん"
    cookie: 85945596_Tu6naZkEsFu5wxosG6K6qRrYQlO8iALw
    # clash 代理默认端口 7890
    proxy: "127.0.0.1:7890"   
    max_pid_len: 20
```

**Comment by cby120** [comment]
可以把项目默认全局编码改为UTF-8
