### ISSUE TITLE
读取未加好友的私聊消息报错

### ISSUE THREAD

**Issue by Minami-Yuduru** [FengLiuFeseliud/pycqBot#33]
每当触发未加好友的私聊消息时就会报错：
Traceback (most recent call last):
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python3.10.7\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python3.10.7\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python3.10.7\lib\site-packages\pycqBot\cqHttpApi.py", line 519, in run_event
    self._run_event(event_name, event)
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python3.10.7\lib\site-packages\pycqBot\cqHttpApi.py", line 452, in _run_event
    event = event.get_message(self.cqapi)
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python3.10.7\lib\site-packages\pycqBot\data\event.py", line 88, in get_message
    return Private_Message(cqapi, self, self.data) if self.is_private() else Group_Message(cqapi, self, self.data)
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python3.10.7\lib\site-packages\pycqBot\data\message.py", line 89, in __init__
    self.target_id: int = message_data["target_id"]

**Comment by Minami-Yuduru** [comment]
将target_id改成user_id可解决此问题

**Comment by SydrrO** [comment]
您好，我是这个脚本的使用者之一，我最近遇到了一些问题，但是他本人一直不回复，我想问问您，如何获取群成员的信息，比我我问他1还是2，我如何将他的回答返回后台呢，谢谢
