### ISSUE TITLE
请问作者是否有个服务器挂掉了?

### ISSUE THREAD

**Issue by leavedrop** [FengLiuFeseliud/pycqBot#38]
成功连上ws服务器 无法接收群消息 一收到消息就会报错 如下

**Comment by leavedrop** [comment]
首次启动，获取历史信息中...
???
错误信息是: 'Group_Message' object has no attribute 'text'
<ClientResponse(http://127.0.0.1:5700/get_group_msg_history) [400 Bad Request]>
<CIMultiDictProxy('Content-Type': 'text/plain; charset=utf-8', 'Sec-WebSocket-Version': '13', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 29 Jun 2023 10:02:47 GMT', 'Content-Length': '12')>

[2023-06-29 18:02:47,197][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 处理 WebSocket 请求时出现错误: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
[2023-06-29 18:02:47,198][asyncHttp_loop/ERROR] PyCqBot: api 请求发生错误 Error: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://127.0.0.1:5700/get_group_msg_history')
[2023-06-29 18:02:47,198][asyncHttp_loop/ERROR] PyCqBot: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://127.0.0.1:5700/get_group_msg_history')
Traceback (most recent call last):
  File "C:\python3\lib\site-packages\pycqBot\asyncHttp.py", line 78, in link
    http_data = await req.json(encoding=encoding)
  File "C:\python3\lib\site-packages\aiohttp\client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://127.0.0.1:5700/get_group_msg_history')
[2023-06-29 18:02:47,199][asyncHttp_loop/WARNING] PyCqBot: cqAPI 响应: None / {}
[2023-06-29 18:03:19,148][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 处理 WebSocket 请求时出现错误: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
[2023-06-29 18:03:19,370][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 处理 WebSocket 请求时出现错误: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
[2023-06-29 18:04:13,718][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 处理 WebSocket 请求时出现错误: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
[2023-06-29 18:04:13,865][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 处理 WebSocket 请求时出现错误: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

**Comment by leavedrop** [comment]
有没有大哥能告诉我如何解决

**Comment by leavedrop** [comment]
破案了   获取群消息的api挂了
